import Link from "next/link";
import { HeroPrompt } from "./_components/HeroPrompt";

const PRIMARY_CTA =
  "inline-flex cursor-pointer items-center gap-2 rounded-lg border-2 border-ink bg-ink px-4 py-2 text-sm font-semibold text-paper shadow-[3px_3px_0_0_#111] transition hover:-translate-y-0.5 hover:shadow-[4px_4px_0_0_#111] active:translate-y-0 active:shadow-[1px_1px_0_0_#111] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-paper";

// Real panels generated by the studio's own API (see public/showcase).
const HERO_PANELS = [
  { src: "/showcase/shonen.jpg", name: "Shōnen", note: "rooftop duel" },
  { src: "/showcase/shojo.jpg", name: "Shōjo", note: "under the blossoms" },
  { src: "/showcase/seinen.jpg", name: "Seinen", note: "neon alley" },
];

const SHOWCASE = [
  { src: "/showcase/shonen.jpg", caption: "Rooftop duel in the rain", meta: "shōnen · panel · b&w" },
  { src: "/showcase/action.jpg", caption: "Charging with a glowing blade", meta: "shōnen · panel · b&w" },
  { src: "/showcase/seinen.jpg", caption: "Detective in a neon alley", meta: "seinen · panel · b&w" },
  { src: "/showcase/character.jpg", caption: "Cyberpunk mercenary sheet", meta: "seinen · character · b&w" },
  { src: "/showcase/shojo.jpg", caption: "Under the cherry blossoms", meta: "shōjo · cover · color" },
  { src: "/showcase/classroom.jpg", caption: "Sunlit classroom laughter", meta: "shōjo · panel · color" },
];

export default function Landing() {
  return (
    <div className="min-h-screen bg-paper text-ink">
      {/* Nav */}
      <header className="sticky top-0 z-40 border-b-2 border-ink bg-paper/85 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6">
          <Link
            href="/"
            className="rounded font-display text-xl font-extrabold tracking-tight focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-paper"
          >
            Manga<span className="text-accent">Forge</span>
          </Link>
          <nav className="flex items-center gap-4 sm:gap-6">
            <a href="#how" className="hidden font-mono text-xs uppercase tracking-widest text-ink-soft hover:text-ink sm:block">
              How it works
            </a>
            <a href="#features" className="hidden font-mono text-xs uppercase tracking-widest text-ink-soft hover:text-ink sm:block">
              Features
            </a>
            <Link href="/editor" className="hidden font-mono text-xs uppercase tracking-widest text-ink-soft hover:text-ink sm:block">
              Editor
            </Link>
            <Link href="/create" className={PRIMARY_CTA}>
              Open studio
            </Link>
          </nav>
        </div>
      </header>

      {/* Hero */}
      <section className="relative overflow-hidden border-b-2 border-ink">
        <div className="halftone pointer-events-none absolute inset-0 text-ink/[0.04]" aria-hidden="true" />
        <div className="relative mx-auto max-w-4xl px-4 py-20 text-center sm:px-6 sm:py-28">
          <span className="inline-flex items-center rounded-full border-2 border-ink bg-white px-3 py-1 font-mono text-[11px] font-semibold uppercase tracking-[0.2em]">
            AI manga studio
          </span>
          <h1 className="mx-auto mt-6 max-w-3xl font-display text-5xl font-extrabold leading-[0.95] tracking-tight sm:text-7xl">
            Forge manga panels from{" "}
            <span className="whitespace-nowrap border-b-4 border-accent text-accent">one line</span>.
          </h1>
          <p className="mx-auto mt-5 max-w-xl text-base text-ink-soft sm:text-lg">
            Describe a scene, choose a style, and get a finished manga panel in seconds — saved to your gallery,
            ready to remix.
          </p>
          <div className="mt-8">
            <HeroPrompt />
          </div>
          <p className="mt-3 font-mono text-xs text-ink-soft">No sign-up · Free · ~10–30s per panel</p>

          {/* Real sample panels — one per genre */}
          <div className="mx-auto mt-14 grid max-w-3xl grid-cols-3 gap-3 sm:gap-4">
            {HERO_PANELS.map((p) => (
              <figure
                key={p.name}
                className="relative aspect-square overflow-hidden rounded-lg border-2 border-ink bg-white shadow-[3px_3px_0_0_#111]"
              >
                {/* eslint-disable-next-line @next/next/no-img-element -- static showcase asset */}
                <img src={p.src} alt={`${p.name} manga sample: ${p.note}`} className="h-full w-full object-cover" />
                <figcaption className="absolute inset-x-0 bottom-0 flex items-center justify-between border-t-2 border-ink bg-white/95 px-2 py-1 font-mono text-[9px] uppercase tracking-widest sm:text-[10px]">
                  <span className="font-bold text-ink">{p.name}</span>
                  <span className="hidden text-ink-soft sm:inline">{p.note}</span>
                </figcaption>
              </figure>
            ))}
          </div>
        </div>
      </section>

      {/* Showcase */}
      <section className="border-b-2 border-ink bg-white">
        <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
          <SectionHeading eyebrow="Showcase" title="Panels forged by the studio" />
          <p className="mt-2 max-w-2xl text-sm text-ink-soft">
            Real outputs from the same free image API the app uses — generated, not cherry-picked stock art.
          </p>
          <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3">
            {SHOWCASE.map((s) => (
              <figure
                key={s.src}
                className="overflow-hidden rounded-xl border-2 border-ink bg-white shadow-[4px_4px_0_0_#111] transition hover:-translate-y-0.5 hover:shadow-[6px_6px_0_0_#111]"
              >
                {/* eslint-disable-next-line @next/next/no-img-element -- static showcase asset */}
                <img
                  src={s.src}
                  alt={s.caption}
                  loading="lazy"
                  className="aspect-square w-full border-b-2 border-ink object-cover"
                />
                <figcaption className="p-3">
                  <p className="truncate text-sm font-medium text-ink">{s.caption}</p>
                  <p className="mt-0.5 font-mono text-[10px] uppercase tracking-widest text-ink-soft">{s.meta}</p>
                </figcaption>
              </figure>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="border-b-2 border-ink">
        <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
          <SectionHeading eyebrow="How it works" title="Three steps to a panel" />
          <ol className="mt-10 grid gap-5 sm:grid-cols-3">
            <StepCard n={1} title="Describe" icon={<IconPencil />}>
              Type a scene and pick genre, format, colour, and screentone. We build a proper manga prompt for you.
            </StepCard>
            <StepCard n={2} title="Forge" icon={<IconSparkles />}>
              Your backend calls the AI and streams the wait live — a real 10–30&nbsp;seconds, no fake instant demo.
            </StepCard>
            <StepCard n={3} title="Save &amp; remix" icon={<IconStar />}>
              Every panel is stored server-side and stays after refresh. Tweak the prompt and regenerate anytime.
            </StepCard>
          </ol>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="border-b-2 border-ink bg-white">
        <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
          <SectionHeading eyebrow="Features" title="Built to actually ship panels" />
          <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            <FeatureCard title="Manga-native controls" icon={<IconSliders />} wide>
              Genre (shōnen / shōjo / seinen), panel vs cover vs character sheet, B&amp;W or colour, and halftone
              screentone — the niche shapes the whole composer, not just the name.
            </FeatureCard>
            <FeatureCard title="Your gallery, saved" icon={<IconLayers />}>
              Panels and their prompts persist server-side and survive a refresh — scoped privately to you, no login.
            </FeatureCard>
            <FeatureCard title="Non-destructive remix" icon={<IconSparkles />}>
              Reopen any panel, tweak the prompt, and forge a new one. The original always stays put.
            </FeatureCard>
            <FeatureCard title="Consistent characters" icon={<IconStar />}>
              Save a result as a character and reuse its seed for a steadier look — honest, best-effort on free models.
            </FeatureCard>
            <FeatureCard title="Handles the messy parts" icon={<IconShield />}>
              Timeouts, blocked prompts, and broken responses each get a clear, distinct card — shown, never hidden.
            </FeatureCard>
            <FeatureCard title="Private by design" icon={<IconLock />}>
              AI calls run only on the backend and images are stored server-side — the browser never touches a key.
            </FeatureCard>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="relative overflow-hidden bg-ink text-paper">
        <div className="halftone absolute inset-0 text-white/[0.06]" aria-hidden="true" />
        <div className="relative mx-auto max-w-3xl px-4 py-20 text-center sm:px-6">
          <h2 className="font-display text-4xl font-extrabold tracking-tight sm:text-5xl">
            Your next panel is one line away.
          </h2>
          <p className="mx-auto mt-4 max-w-lg text-paper/70">
            Open the studio, describe a scene, and watch it come back inked in seconds.
          </p>
          <Link
            href="/create"
            className="mt-8 inline-flex cursor-pointer items-center gap-2 rounded-lg border-2 border-paper bg-paper px-6 py-3 text-sm font-semibold text-ink shadow-[3px_3px_0_0_rgba(255,255,255,0.25)] transition hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-ink"
          >
            Open the studio →
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t-2 border-ink bg-paper">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-3 px-4 py-8 sm:flex-row sm:px-6">
          <span className="font-display text-lg font-extrabold">
            Manga<span className="text-accent">Forge</span>
          </span>
          <p className="text-center font-mono text-[11px] uppercase tracking-widest text-ink-soft">
            Free-tier models · character consistency is best-effort · handles its own failures
          </p>
        </div>
      </footer>
    </div>
  );
}

/* ------------------------------ Presentational --------------------------- */

function SectionHeading({ eyebrow, title }: { eyebrow: string; title: string }) {
  return (
    <div className="max-w-2xl">
      <span className="font-mono text-xs font-semibold uppercase tracking-[0.2em] text-accent">{eyebrow}</span>
      <h2 className="mt-2 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">{title}</h2>
    </div>
  );
}

function StepCard({
  n,
  title,
  icon,
  children,
}: {
  n: number;
  title: React.ReactNode;
  icon: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <li className="rounded-xl border-2 border-ink bg-white p-5 shadow-[4px_4px_0_0_#111]">
      <div className="flex items-center justify-between">
        <span className="font-mono text-3xl font-bold text-ink/20">0{n}</span>
        <span className="text-accent">{icon}</span>
      </div>
      <h3 className="mt-3 font-display text-xl font-bold">{title}</h3>
      <p className="mt-1.5 text-sm text-ink-soft">{children}</p>
    </li>
  );
}

function FeatureCard({
  title,
  icon,
  children,
  wide = false,
}: {
  title: string;
  icon: React.ReactNode;
  children: React.ReactNode;
  wide?: boolean;
}) {
  return (
    <div className={`rounded-xl border-2 border-ink bg-paper p-5 shadow-[4px_4px_0_0_#111] ${wide ? "sm:col-span-2" : ""}`}>
      <span className="inline-flex h-9 w-9 items-center justify-center rounded-lg border-2 border-ink bg-accent/10 text-accent">
        {icon}
      </span>
      <h3 className="mt-3 font-display text-lg font-bold">{title}</h3>
      <p className="mt-1.5 text-sm text-ink-soft">{children}</p>
    </div>
  );
}

/* --------------------------------- Icons --------------------------------- */

function Svg({ children, className = "h-5 w-5" }: { children: React.ReactNode; className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
      aria-hidden="true"
    >
      {children}
    </svg>
  );
}

const IconSparkles = () => (
  <Svg>
    <path d="M12 3v4M12 17v4M3 12h4M17 12h4" />
    <path d="M12 7l1.7 3.3L17 12l-3.3 1.7L12 17l-1.7-3.3L7 12l3.3-1.7z" />
  </Svg>
);
const IconStar = () => (
  <Svg>
    <path d="M12 2l2.9 6.9 7.1.6-5.4 4.7 1.6 7L12 18l-6.2 3.2 1.6-7L2 9.5l7.1-.6z" />
  </Svg>
);
const IconPencil = () => (
  <Svg>
    <path d="M12 20h9" />
    <path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4z" />
  </Svg>
);
const IconSliders = () => (
  <Svg>
    <path d="M4 21v-7M4 10V3M12 21v-9M12 8V3M20 21v-5M20 12V3M1 14h6M9 8h6M17 16h6" />
  </Svg>
);
const IconLayers = () => (
  <Svg>
    <path d="M12 2 2 7l10 5 10-5-10-5z" />
    <path d="M2 17l10 5 10-5M2 12l10 5 10-5" />
  </Svg>
);
const IconShield = () => (
  <Svg>
    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
    <path d="M12 8v4M12 16h.01" />
  </Svg>
);
const IconLock = () => (
  <Svg>
    <rect x="3" y="11" width="18" height="11" rx="2" />
    <path d="M7 11V7a5 5 0 0 1 10 0v4" />
  </Svg>
);
